# Generated by Django 3.1.1 on 2020-10-05 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20200921_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('comment', models.TextField(blank=True,
                                             max_length=1000, null=True)),
                ('rating', models.FloatField(default=1)),
                ('product', models.ForeignKey(blank=True, null=True,
                                              on_delete=django.
                                              db.models.deletion.CASCADE,
                                              related_name='reviews',
                                              to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.
                                           db.models.deletion.CASCADE,
                                           related_name='reviews',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
